import { User, Unit, Vehicle, Notice, FineNotice, CommonSpace, Reservation, DocumentLink, InAppNotification } from '@/types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-1',
    name: 'Carlos Mendes',
    email: 'sindico@harmony.com',
    role: 'SINDICO',
    cargo: 'Síndico Geral (Gestão 2025-2027)',
    bloco: 'A',
    unidade: '101',
    telefone: '(11) 98765-4321',
  },
  {
    id: 'usr-2',
    name: 'Vigilância & Portaria Central',
    email: 'portaria@harmony.com',
    role: 'PORTARIA',
    cargo: 'Operador de Portaria e Monitoramento',
    telefone: '(11) 97123-8899',
  },
  {
    id: 'usr-3',
    name: 'Dra. Renata Lima',
    email: 'conselho@harmony.com',
    role: 'CONSELHO',
    cargo: 'Presidente do Conselho Fiscal',
    bloco: 'B',
    unidade: '402',
    telefone: '(11) 99442-1100',
  },
  {
    id: 'usr-4',
    name: 'Felipe Vieira',
    email: 'felipe@harmony.com',
    role: 'MORADOR',
    cargo: 'Morador Residente',
    bloco: 'A',
    unidade: '304',
    telefone: '(11) 98111-2233',
  },
];

export const INITIAL_UNITS: Unit[] = [
  {
    id: 'unit-101-a',
    bloco: 'A',
    numero: '101',
    proprietarioNome: 'Carlos Mendes',
    proprietarioTelefone: '(11) 98765-4321',
    proprietarioEmail: 'carlos.mendes@email.com',
    tipoOcupacao: 'PROPRIETARIO',
    moradores: [
      { nome: 'Carlos Mendes', tipo: 'TITULAR', telefone: '(11) 98765-4321', rgCpf: '12.345.678-9' },
      { nome: 'Mariana Mendes', tipo: 'DEPENDENTE', telefone: '(11) 98765-4322' },
    ],
    vagasGaragem: ['G1-12', 'G1-13'],
    animais: '1 cachorro (Golden Retriever - Max)',
  },
  {
    id: 'unit-304-a',
    bloco: 'A',
    numero: '304',
    proprietarioNome: 'Felipe Vieira',
    proprietarioTelefone: '(11) 98111-2233',
    proprietarioEmail: 'felipe@harmony.com',
    tipoOcupacao: 'PROPRIETARIO',
    moradores: [
      { nome: 'Felipe Vieira', tipo: 'TITULAR', telefone: '(11) 98111-2233', rgCpf: '29.876.543-2' },
      { nome: 'Camila Santos', tipo: 'DEPENDENTE', telefone: '(11) 98222-3344' },
    ],
    vagasGaragem: ['G2-45'],
    animais: '1 gato (Siamês - Oliver)',
  },
  {
    id: 'unit-202-a',
    bloco: 'A',
    numero: '202',
    proprietarioNome: 'Eduardo Silveira',
    proprietarioTelefone: '(11) 97555-1122',
    proprietarioEmail: 'eduardo@investimentos.com',
    tipoOcupacao: 'INQUILINO',
    moradores: [
      { nome: 'Juliana Paes Costa', tipo: 'INQUILINO', telefone: '(11) 99123-4567', rgCpf: '33.111.222-5' },
    ],
    vagasGaragem: ['G1-22'],
    animais: 'Nenhum',
  },
  {
    id: 'unit-402-b',
    bloco: 'B',
    numero: '402',
    proprietarioNome: 'Renata Lima',
    proprietarioTelefone: '(11) 99442-1100',
    proprietarioEmail: 'renata.lima@advocacia.com',
    tipoOcupacao: 'PROPRIETARIO',
    moradores: [
      { nome: 'Renata Lima', tipo: 'TITULAR', telefone: '(11) 99442-1100', rgCpf: '18.999.888-1' },
      { nome: 'Lucas Lima Prado', tipo: 'DEPENDENTE', telefone: '(11) 99442-1101' },
    ],
    vagasGaragem: ['G2-10', 'G2-11'],
    animais: '2 gatos',
  },
  {
    id: 'unit-501-b',
    bloco: 'B',
    numero: '501',
    proprietarioNome: 'Roberto Justus Filho',
    proprietarioTelefone: '(11) 98333-7766',
    proprietarioEmail: 'roberto.justus@corp.com',
    tipoOcupacao: 'PROPRIETARIO',
    moradores: [
      { nome: 'Roberto Justus Filho', tipo: 'TITULAR', telefone: '(11) 98333-7766' },
    ],
    vagasGaragem: ['G1-04'],
    animais: 'Nenhum',
  },
];

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'veh-1',
    placa: 'BRA2E19',
    marca: 'Toyota',
    modelo: 'Corolla Cross XRE',
    cor: 'Branco Perolizado',
    bloco: 'A',
    unidade: '304',
    vaga: 'G2-45',
    proprietarioNome: 'Felipe Vieira',
    telefoneContato: '(11) 98111-2233',
    status: 'ATIVO',
  },
  {
    id: 'veh-2',
    placa: 'RKO8A77',
    marca: 'Jeep',
    modelo: 'Compass Limited',
    cor: 'Cinza Granite',
    bloco: 'A',
    unidade: '101',
    vaga: 'G1-12',
    proprietarioNome: 'Carlos Mendes',
    telefoneContato: '(11) 98765-4321',
    status: 'ATIVO',
  },
  {
    id: 'veh-3',
    placa: 'EGA4421',
    marca: 'Honda',
    modelo: 'Civic Touring',
    cor: 'Preto Cristal',
    bloco: 'B',
    unidade: '402',
    vaga: 'G2-10',
    proprietarioNome: 'Renata Lima',
    telefoneContato: '(11) 99442-1100',
    status: 'ATIVO',
  },
  {
    id: 'veh-4',
    placa: 'FDZ9980',
    marca: 'Hyundai',
    modelo: 'HB20 Evolution',
    cor: 'Prata Sand',
    bloco: 'A',
    unidade: '202',
    vaga: 'G1-22',
    proprietarioNome: 'Juliana Paes Costa',
    telefoneContato: '(11) 99123-4567',
    status: 'ATIVO',
  },
  {
    id: 'veh-5',
    placa: 'BMW3X20',
    marca: 'BMW',
    modelo: '320i M Sport',
    cor: 'Azul Portimao',
    bloco: 'B',
    unidade: '501',
    vaga: 'G1-04',
    proprietarioNome: 'Roberto Justus Filho',
    telefoneContato: '(11) 98333-7766',
    status: 'ATIVO',
  },
];

export const INITIAL_NOTICES: Notice[] = [
  {
    id: 'not-1',
    titulo: 'Convocação para Assembleia Geral Ordinária (AGO 2026)',
    categoria: 'ASSEMBLEIA',
    data: '2026-09-18',
    autor: 'Síndico Geral',
    fixado: true,
    conteudo: 'Ficam todos os senhores condôminos convocados para a AGO que deliberará sobre a prestação de contas do último exercício, previsão orçamentária para 2027 e eleição do novo conselho.',
    anexoNome: 'Edital_AGO_2026_Assinado.pdf',
  },
  {
    id: 'not-2',
    titulo: 'Manutenção Preventiva dos Elevadores - Bloco A',
    categoria: 'MANUTENCAO',
    data: '2026-09-16',
    autor: 'Administração Predial',
    fixado: false,
    conteudo: 'Informamos que nesta quinta-feira das 09h às 12h o elevador social do Bloco A estará interditado para troca preventiva de cabos de tração. O elevador de serviço funcionará normalmente.',
  },
  {
    id: 'not-3',
    titulo: 'Campanha de Convivência: Respeito à Lei do Silêncio após 22h',
    categoria: 'COMUNICADO',
    data: '2026-09-10',
    autor: 'Conselho Consultivo',
    fixado: false,
    conteudo: 'Relembramos aos moradores e hóspedes as diretrizes do Art. 42 do Regimento Interno sobre emissão sonora e ruídos excessivos. O bom senso constrói a tranquilidade de todos.',
    anexoNome: 'Cartilha_Boas_Praticas_Harmony.pdf',
  },
];

export const INITIAL_FINES: FineNotice[] = [
  {
    id: 'fine-001',
    numeroProtocolo: 'NOT-2026/089',
    bloco: 'A',
    unidade: '304',
    moradorNome: 'Felipe Vieira',
    dataInfracao: '2026-09-08 23:45',
    dataEmissao: '2026-09-09',
    prazoRecursoData: '2026-09-24',
    artigoRegimento: 'Artigo 42, § 2º - Ruído excessivo após o horário de silêncio (22h)',
    descricaoInfracao: 'Constatado som em volume elevado e algazarra na unidade após às 23h30, gerando reclamações formais no livro da portaria pelas unidades 303 e 404.',
    valor: 450.00,
    tipo: 'MULTA',
    status: 'PENDENTE_CIENCIA',
    evidencias: [
      {
        id: 'ev-1',
        url: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&auto=format&fit=crop&q=60',
        descricao: 'Registro de decibelímetro na circulação do 3º andar acusando 78dB às 23h45.',
      },
      {
        id: 'ev-2',
        url: 'https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?w=800&auto=format&fit=crop&q=60',
        descricao: 'Ocorrência registrada no livro da portaria assinada pelo vigilante de plantão.',
      }
    ],
  },
  {
    id: 'fine-002',
    numeroProtocolo: 'NOT-2026/075',
    bloco: 'B',
    unidade: '501',
    moradorNome: 'Roberto Justus Filho',
    dataInfracao: '2026-08-28 14:15',
    dataEmissao: '2026-08-29',
    prazoRecursoData: '2026-09-12',
    artigoRegimento: 'Artigo 18, Inciso IV - Estacionamento irregular fora da demarcação da vaga',
    descricaoInfracao: 'Veículo BMW placa BMW3X20 estacionado obstruindo a faixa de manobra da garagem G1.',
    valor: 0.00,
    tipo: 'ADVERTENCIA',
    status: 'CIENCIA_REGISTRADA',
    ciencia: {
      data: '2026-08-30 08:22',
      ip: '187.54.120.45',
      usuarioNome: 'Roberto Justus Filho',
    },
    evidencias: [
      {
        id: 'ev-3',
        url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&auto=format&fit=crop&q=60',
        descricao: 'Foto da câmera de monitoramento C-04 da garagem G1.',
      }
    ],
  },
  {
    id: 'fine-003',
    numeroProtocolo: 'NOT-2026/062',
    bloco: 'A',
    unidade: '202',
    moradorNome: 'Juliana Paes Costa',
    dataInfracao: '2026-08-15 19:30',
    dataEmissao: '2026-08-16',
    prazoRecursoData: '2026-08-31',
    artigoRegimento: 'Artigo 55 - Descarte inadequado de entulho em área comum',
    descricaoInfracao: 'Depósito de caixas e sacos de reforma na antecâmara do elevador de serviço.',
    valor: 350.00,
    tipo: 'MULTA',
    status: 'EM_RECURSO',
    ciencia: {
      data: '2026-08-17 10:14',
      ip: '177.34.88.12',
      usuarioNome: 'Juliana Paes Costa',
    },
    recurso: {
      data: '2026-08-20 16:30',
      texto: 'Os sacos ficaram no local por apenas 20 minutos enquanto o caminhão de frete manobrava na calçada para recolher. Não houve intenção de abandono de entulho.',
      anexoNome: 'Comprovante_Frete_Entulho.pdf',
      status: 'EM_ANALISE',
    },
    evidencias: [
      {
        id: 'ev-4',
        url: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=800&auto=format&fit=crop&q=60',
        descricao: 'Evidência fotográfica enviada pela zeladoria.',
      }
    ],
  },
];

export const INITIAL_SPACES: CommonSpace[] = [
  {
    id: 'spc-1',
    nome: 'Salão de Festas Nobre',
    descricao: 'Ambiente climatizado com capacidade para até 80 pessoas, cozinha completa equipada com fogão industrial, cervejeira, freezer e sistema de som integrado.',
    capacidadeMax: 80,
    horarioFuncionamento: '10:00 às 23:00',
    taxaLimpeza: 150.00,
    regras: [
      'Reserva deve ser solicitada com no mínimo 48h de antecedência.',
      'Obrigatória aprovação expressa do síndico.',
      'A música deve ser desligada pontualmente às 22h00.',
      'Vistoria de entrada e saída realizada junto à portaria.',
    ],
    imagemUrl: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800&auto=format&fit=crop&q=60',
  },
  {
    id: 'spc-2',
    nome: 'Espaço Gourmet & Churrasqueira',
    descricao: 'Área com churrasqueira a carvão, forno de pizza a lenha, mesas rústicas e vista para a piscina. Ideal para confraternizações de até 35 pessoas.',
    capacidadeMax: 35,
    horarioFuncionamento: '11:00 às 22:00',
    taxaLimpeza: 90.00,
    regras: [
      'Proibido copos e recipientes de vidro no entorno da piscina.',
      'Limpeza de grelhas e bancadas inclusa na taxa.',
      'Limite de 1 reserva por mês por unidade.',
    ],
    imagemUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop&q=60',
  },
  {
    id: 'spc-3',
    nome: 'Quadra Poliesportiva',
    descricao: 'Quadra com piso emborrachado oficial para futebol de salão, basquete e vôlei, com iluminação LED noturna.',
    capacidadeMax: 20,
    horarioFuncionamento: '08:00 às 21:30',
    taxaLimpeza: 0.00,
    regras: [
      'Uso obrigatório de calçado apropriado (tênis sem cravos).',
      'Turnos máximos de 2 horas por unidade.',
      'Menores de 10 anos acompanhados de responsáveis.',
    ],
    imagemUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&auto=format&fit=crop&q=60',
  },
];

export const INITIAL_RESERVATIONS: Reservation[] = [
  {
    id: 'res-101',
    espacoId: 'spc-2',
    espacoNome: 'Espaço Gourmet & Churrasqueira',
    bloco: 'A',
    unidade: '304',
    moradorNome: 'Felipe Vieira',
    data: '2026-09-20',
    horarioInicio: '12:00',
    horarioFim: '18:00',
    convidadosEstimados: 18,
    status: 'PENDENTE',
    dataSolicitacao: '2026-09-14 10:30',
  },
  {
    id: 'res-102',
    espacoId: 'spc-1',
    espacoNome: 'Salão de Festas Nobre',
    bloco: 'B',
    unidade: '402',
    moradorNome: 'Renata Lima',
    data: '2026-09-26',
    horarioInicio: '18:00',
    horarioFim: '23:00',
    convidadosEstimados: 50,
    status: 'APROVADA',
    dataSolicitacao: '2026-09-05 14:00',
    dataAvaliacao: '2026-09-06 09:15',
    avaliadoPor: 'Carlos Mendes (Síndico)',
  },
  {
    id: 'res-103',
    espacoId: 'spc-2',
    espacoNome: 'Espaço Gourmet & Churrasqueira',
    bloco: 'A',
    unidade: '101',
    moradorNome: 'Carlos Mendes',
    data: '2026-09-27',
    horarioInicio: '11:30',
    horarioFim: '17:30',
    convidadosEstimados: 25,
    status: 'APROVADA',
    dataSolicitacao: '2026-09-08 11:20',
    dataAvaliacao: '2026-09-08 11:20',
    avaliadoPor: 'Auto-Aprovado',
  },
];

export const INITIAL_DOCS: DocumentLink[] = [
  {
    id: 'doc-1',
    titulo: 'Convenção Condominial Registrada',
    descricao: 'Texto integral da convenção de constituição do Condomínio Harmony Residence registrada no 4º Cartório de Registro de Imóveis.',
    categoria: 'CONVENCAO',
    arquivoNome: 'Convencao_Harmony_Oficial.pdf',
    tamanhoArquivo: '2.8 MB',
    dataAtualizacao: '15/01/2024',
  },
  {
    id: 'doc-2',
    titulo: 'Regimento Interno Atualizado (Revisão 2025)',
    descricao: 'Normas de conduta, utilização da garagem, horários de mudança, barulho e uso das áreas sociais.',
    categoria: 'REGIMENTO',
    arquivoNome: 'Regimento_Interno_Revisado_2025.pdf',
    tamanhoArquivo: '1.4 MB',
    dataAtualizacao: '10/06/2025',
  },
  {
    id: 'doc-3',
    titulo: 'Ata da Assembleia Geral Extraordinária - Março/2026',
    descricao: 'Aprovação da reforma dos elevadores e implantação do novo sistema digital de gestão.',
    categoria: 'ATA',
    arquivoNome: 'Ata_AGE_Março_2026.pdf',
    tamanhoArquivo: '850 KB',
    dataAtualizacao: '20/03/2026',
  },
  {
    id: 'doc-4',
    titulo: 'Portaria & Vigilância 24 Horas',
    descricao: 'Canal direto com a guarita para autorização de visitantes, emergências e entregas.',
    categoria: 'EMERGENCIA',
    telefone: '(11) 3210-0001 / Ramal 94',
    dataAtualizacao: 'Permanente',
  },
  {
    id: 'doc-5',
    titulo: 'Zeladoria e Manutenção Predial',
    descricao: 'Zelador Sr. Antonio - Atendimento das 08h às 17h para reparos em áreas comuns.',
    categoria: 'EMERGENCIA',
    telefone: '(11) 98777-6655 / Ramal 91',
    dataAtualizacao: 'Permanente',
  },
  {
    id: 'doc-6',
    titulo: 'Administradora Predial (Lello / BRCondos)',
    descricao: 'Segunda via de boletos de condomínio, certidões negativas de débito e suporte financeiro.',
    categoria: 'FINANCEIRO',
    linkExterno: 'https://www.administradoraexemplo.com.br/portal',
    telefone: '0800 770 1234',
    dataAtualizacao: 'Diária',
  },
];

export const INITIAL_NOTIFICATIONS: InAppNotification[] = [
  {
    id: 'notif-1',
    titulo: 'Nova Notificação Disciplinar Registrada',
    mensagem: 'Foi emitida a notificação NOT-2026/089 para a Unidade 304 referente a ruídos. Favor confirmar ciência.',
    tipo: 'MULTA',
    data: '09/09/2026 às 10:15',
    lida: false,
    unidadeAlvo: '304',
    linkDestino: '/multas/fine-001',
  },
  {
    id: 'notif-2',
    titulo: 'Solicitação de Reserva Aguardando Aprovação',
    mensagem: 'Felipe Vieira (Apto 304) solicitou a Churrasqueira para 20/09/2026.',
    tipo: 'RESERVA',
    data: '14/09/2026 às 10:30',
    lida: false,
    perfilAlvo: 'SINDICO',
    linkDestino: '/reservas',
  },
  {
    id: 'notif-3',
    titulo: 'Assembleia Geral Ordinária Agendada',
    mensagem: 'Aviso importante publicado no mural sobre a AGO de 18 de Setembro.',
    tipo: 'AVISO',
    data: '12/09/2026 às 09:00',
    lida: true,
    linkDestino: '/mural',
  },
];
